port: 16668
log_level: debug
service:
  name: FeedReader
  interval: 300 # 5分毎にチェック
  bot_name: feed
  channels:
    '#haiku':
      feeds:
        - uri: http://h.hatena.ne.jp/wakabatan/following.rss
